import {evaluateBadges,weekKey,weekSummary,validRewards} from '../rewards.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {program,kg,displayWeight,keyFor,recommendation,weeklyVolume} from '../program.js';
function harness(){const events=[];let source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'');source=source.slice(0,source.lastIndexOf("document.querySelectorAll('[data-view]')"));source+='\nrender=()=>{};toast=()=>{};globalThis.api={valid,exerciseDraft,finish,warmupHTML,rewardProgress,currentBadges,setState:s=>state=s,getState:()=>state};';const context={evaluateBadges,weekKey,weekSummary,validRewards,celebrate:event=>events.push(event),badgeRow:()=>'',program,kg,displayWeight,keyFor,recommendation,weeklyVolume,localStorage:{getItem:()=>null,setItem:()=>{}},document:{querySelector:()=>({})},confirm:()=>true,crypto:{randomUUID:()=> 'test-session'},window:{scrollTo:()=>{}},setTimeout,clearTimeout};vm.runInNewContext(source,context);context.api.events=events;return context.api}
const empty=()=>({version:1,unit:'lb',day:'A',history:[],drafts:{}});
test('existing backups and drafts remain valid',()=>{const h=harness(),s=empty();assert.equal(h.valid(s),true);h.setState(s);const d=h.exerciseDraft(program[0].exercises[0]);delete d.warmups;assert.equal(h.valid(s),true);assert.equal(h.exerciseDraft(program[0].exercises[0]).warmups.length,0)});
test('warm-up sets save separately, preserve weights and validate',()=>{const h=harness(),s=empty();h.setState(s);const d=h.exerciseDraft(program[0].exercises[0]);d.warmups.push({weight:kg(50,'lb'),reps:8,rir:4,done:true});d.sets[0]={weight:kg(100,'lb'),reps:8,rir:2,done:true};h.finish();const saved=h.getState();assert.equal(saved.history[0].exercises[0].warmups.length,1);assert.equal(saved.history[0].exercises[0].sets.length,1);assert.equal(displayWeight(saved.history[0].exercises[0].warmups[0].weight,'lb'),50);assert.equal(h.valid(saved),true);saved.history[0].exercises[0].warmups[0].reps=-1;assert.equal(h.valid(saved),false)});
test('warm-up-only sessions save without changing work progression',()=>{const h=harness();h.setState(empty());const e=program[0].exercises[0],d=h.exerciseDraft(e);d.warmups.push({weight:kg(50,'lb'),reps:8,rir:4,done:true});h.finish();const s=h.getState();assert.equal(s.history[0].exercises[0].sets.length,0);assert.equal(recommendation(e,e.name,s.history,'lb').weight,null)});
test('old history survives removed exercise and reduced set counts',()=>{const h=harness(),s=empty();s.history=[{id:'old',date:new Date().toISOString(),day:'C',deload:false,note:'',exercises:[{name:'Machine hip thrust',key:'hip:Machine hip thrust',sets:Array.from({length:3},()=>({weight:50,reps:10,rir:2,done:true}))}]}];assert.equal(h.valid(s),true)});

test('earned coins survive finish and backup validation without duplicate splash',()=>{const h=harness(),s=empty(),e=program[0].exercises[0];s.history=[{id:'baseline',date:'2026-10-01T12:00:00Z',day:'A',deload:false,note:'',exercises:[{key:keyFor(e),name:e.name,sets:[{weight:50,reps:8,rir:2,done:true}]}]}];h.setState(s);const d=h.exerciseDraft(e);d.sets=d.sets.map(()=>({weight:50,reps:9,rir:2,done:true}));h.rewardProgress();h.rewardProgress();assert.equal(h.events.length,1);assert.equal(h.events[0].kind,'muscle');h.finish();assert.equal(h.getState().history.at(-1).rewards.badges.length,1);assert.equal(h.valid(h.getState()),true)});
test('three full days produce day recaps and one weekly recap even with zero coins',()=>{const h=harness();h.setState(empty());for(let i=0;i<3;i++){const w=program[i];for(const e of w.exercises){const d=h.exerciseDraft(e);d.sets=d.sets.map(()=>({weight:e.kind==='body'?0:50,reps:e.min,rir:2,done:true}))}h.finish()}assert.deepEqual(h.events.map(e=>e.kind),['day','day','day','week']);assert.equal(h.events.at(-1).badges.length,0);assert.equal(h.getState().history.length,3)});
